services:
  shrtnr:
    container_name: shrtnr 
    build: .
    ports:
      - "8080:8080"
    environment:
      - "REDIS_ADDR=redis:6379"
      - "REDIS_PASSWORD=CHANGEME"
    depends_on:
      - redis
  
  redis:
    container_name: redis 
    image: redis:6.0.20-alpine
    ports:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass CHANGEME
    volumes: 
      - cache:/data
  
volumes:
  cache:
    driver: local